
package wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UAWebService", targetNamespace = "http://lgs.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UAWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://lgs.com.cn/", className = "wsdl.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://lgs.com.cn/", className = "wsdl.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddressByNumber", targetNamespace = "http://lgs.com.cn/", className = "wsdl.GetAddressByNumber")
    @ResponseWrapper(localName = "getAddressByNumberResponse", targetNamespace = "http://lgs.com.cn/", className = "wsdl.GetAddressByNumberResponse")
    public String getAddressByNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
