
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UAWebServiceService", targetNamespace = "http://lgs.com.cn/", wsdlLocation = "http://127.0.0.1:8889/mobile?wsdl")
public class UAWebServiceService
    extends Service
{

    private final static URL UAWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException UAWEBSERVICESERVICE_EXCEPTION;
    private final static QName UAWEBSERVICESERVICE_QNAME = new QName("http://lgs.com.cn/", "UAWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8889/mobile?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UAWEBSERVICESERVICE_WSDL_LOCATION = url;
        UAWEBSERVICESERVICE_EXCEPTION = e;
    }

    public UAWebServiceService() {
        super(__getWsdlLocation(), UAWEBSERVICESERVICE_QNAME);
    }

    public UAWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UAWEBSERVICESERVICE_QNAME, features);
    }

    public UAWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, UAWEBSERVICESERVICE_QNAME);
    }

    public UAWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UAWEBSERVICESERVICE_QNAME, features);
    }

    public UAWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UAWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UAWebService
     */
    @WebEndpoint(name = "UAWebServicePort")
    public UAWebService getUAWebServicePort() {
        return super.getPort(new QName("http://lgs.com.cn/", "UAWebServicePort"), UAWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UAWebService
     */
    @WebEndpoint(name = "UAWebServicePort")
    public UAWebService getUAWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://lgs.com.cn/", "UAWebServicePort"), UAWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UAWEBSERVICESERVICE_EXCEPTION!= null) {
            throw UAWEBSERVICESERVICE_EXCEPTION;
        }
        return UAWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
