
package wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UAWebServiceImpl", targetNamespace = "http://lgs.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UAWebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getString", targetNamespace = "http://lgs.com.cn/", className = "wsdl.GetString")
    @ResponseWrapper(localName = "getStringResponse", targetNamespace = "http://lgs.com.cn/", className = "wsdl.GetStringResponse")
    @Action(input = "http://lgs.com.cn/UAWebServiceImpl/getStringRequest", output = "http://lgs.com.cn/UAWebServiceImpl/getStringResponse")
    public String getString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
